base: 'https://typo3forum.ddev.site/'
rootPageId: 1
websiteTitle: 'TYPO3 Forum development'
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    hreflang: en-US
    flag: us
imports:
  - resource: 'EXT:typo3_forum/Configuration/Routing/Routing.yaml'
