name: typo3forum
type: typo3
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.11"
composer_version: "2"
xdebug_enabled: false
use_dns_when_possible: true
web_environment:
  - TYPO3_CONTEXT=Development
